import type { CSSProperties } from "react";

type AuthStyleMap = Record<string, CSSProperties>;

const palette = {
  bg: "#050a16",
  surface: "rgba(10, 15, 28, 0.92)",
  border: "rgba(255, 255, 255, 0.08)",
  text: "#e7ecf7",
  muted: "#9fb1cc",
  accent: "#60a5fa",
  accent2: "#38bdf8",
} as const;

const fontStack = '"Space Grotesk", "Sora", system-ui, -apple-system, sans-serif';
const glow = "0 22px 58px rgba(5, 10, 20, 0.55)";

const styles: AuthStyleMap = {
  page: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    padding: "clamp(28px, 5vw, 42px) clamp(12px, 4vw, 16px) clamp(48px, 6vw, 64px)",
    background: `radial-gradient(120% 140% at 10% 18%, rgba(56, 189, 248, 0.08), transparent),
      radial-gradient(120% 140% at 82% -4%, rgba(96, 165, 250, 0.08), transparent),
      ${palette.bg}`,
    color: palette.text,
    fontFamily: fontStack,
  },
  card: {
    position: "relative",
    width: "100%",
    maxWidth: "1080px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "clamp(16px, 2vw, 26px)",
    padding: "clamp(20px, 4vw, 32px)",
    background: "linear-gradient(145deg, rgba(13, 21, 36, 0.95), rgba(8, 13, 24, 0.9))",
    border: `1px solid ${palette.border}`,
    borderRadius: "clamp(18px, 2vw, 26px)",
    boxShadow: `${glow}, 0 0 0 1px rgba(56, 189, 248, 0.08)`,
    overflow: "hidden",
    backdropFilter: "blur(14px)",
  },
  orb: {
    position: "absolute",
    inset: "-60px auto auto -60px",
    width: "220px",
    height: "220px",
    background: "radial-gradient(circle at 30% 30%, rgba(96, 165, 250, 0.24), transparent)",
    filter: "blur(12px)",
    opacity: 0.65,
    pointerEvents: "none",
  },
  orbAlt: {
    position: "absolute",
    inset: "auto -60px -60px auto",
    width: "200px",
    height: "200px",
    background: "radial-gradient(circle at 60% 40%, rgba(56, 189, 248, 0.2), transparent)",
    filter: "blur(18px)",
    opacity: 0.55,
    pointerEvents: "none",
  },
  hero: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gap: "clamp(8px, 1.5vw, 12px)",
  },
  eyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    width: "fit-content",
    padding: "8px 12px",
    borderRadius: "999px",
    border: `1px solid ${palette.border}`,
    background: "rgba(255, 255, 255, 0.05)",
    fontSize: "12px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: palette.muted,
    fontWeight: 700,
  },
  title: {
    margin: "0",
    fontSize: "clamp(28px, 4vw, 36px)",
    letterSpacing: "-0.4px",
    color: "#f8fafc",
  },
  subtitle: {
    margin: "0",
    color: palette.muted,
    lineHeight: 1.6,
    maxWidth: "480px",
  },
  form: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gap: "clamp(12px, 2vw, 16px)",
  },
  field: {
    display: "grid",
    gap: "6px",
  },
  label: {
    fontSize: "13px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: palette.muted,
    fontWeight: 700,
  },
  input: {
    width: "100%",
    padding: "13px 14px",
    borderRadius: "14px",
    border: `1px solid ${palette.border}`,
    background: "rgba(255, 255, 255, 0.04)",
    color: palette.text,
    fontSize: "15px",
    outline: "none",
    transition:
      "border-color 0.2s ease, box-shadow 0.2s ease, background 0.2s ease, transform 0.2s ease",
  },
  inputFocus: {
    borderColor: "rgba(96, 165, 250, 0.7)",
    boxShadow: "0 0 0 4px rgba(56, 189, 248, 0.14)",
    background: "rgba(255, 255, 255, 0.08)",
    transform: "translateY(-1px)",
  },
  hint: {
    fontSize: "13px",
    color: palette.muted,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    marginTop: "4px",
    flexWrap: "wrap",
    width: "100%",
    justifyContent: "center",
  },
  submit: {
    flex: "1 1 220px",
    minWidth: "min(260px, 100%)",
    border: "none",
    background: `linear-gradient(120deg, ${palette.accent} 0%, ${palette.accent2} 100%)`,
    color: "#04101f",
    padding: "13px 16px",
    borderRadius: "14px",
    fontWeight: 800,
    letterSpacing: "0.15px",
    boxShadow: "0 12px 34px rgba(56, 189, 248, 0.36)",
    cursor: "pointer",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  submitHover: {
    transform: "translateY(-1px)",
    boxShadow: "0 16px 46px rgba(56, 189, 248, 0.48)",
  },
  ghostButton: {
    flex: "1 1 220px",
    minWidth: "min(260px, 100%)",
    background: "rgba(255, 255, 255, 0.06)",
    border: `1px solid ${palette.border}`,
    color: palette.text,
    padding: "13px 16px",
    borderRadius: "14px",
    fontWeight: 700,
    cursor: "pointer",
    transition: "transform 0.2s ease, border-color 0.2s ease, background 0.2s ease",
  },
  ghostButtonHover: {
    transform: "translateY(-1px)",
    borderColor: "rgba(56, 189, 248, 0.4)",
    background: "rgba(56, 189, 248, 0.08)",
  },
  footer: {
    textAlign: "center",
    marginTop: "8px",
    color: palette.muted,
    fontSize: "14px",
  },
  link: {
    color: palette.accent,
    fontWeight: 700,
    textDecoration: "none",
  },
  featureCard: {
    position: "relative",
    zIndex: 1,
    alignSelf: "stretch",
    padding: "18px 16px",
    background: "rgba(255, 255, 255, 0.03)",
    borderRadius: "18px",
    border: `1px solid ${palette.border}`,
    boxShadow: "0 14px 32px rgba(5, 10, 20, 0.4)",
    display: "grid",
    gap: "10px",
  },
  featureTitle: {
    margin: "0",
    fontSize: "16px",
    letterSpacing: "0.1px",
    color: "#f8fafc",
  },
  featureText: {
    margin: "0",
    color: palette.muted,
    lineHeight: 1.5,
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 12px",
    borderRadius: "12px",
    color: palette.text,
    background: "linear-gradient(120deg, rgba(96, 165, 250, 0.12), rgba(56, 189, 248, 0.08))",
    border: `1px solid ${palette.border}`,
    fontWeight: 700,
  },
  buttonLabel: {
    display: "block",
    whiteSpace: "nowrap",
    overflowX: "auto",
    textAlign: "center",
    width: "100%",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0, 0, 0, 0.6)",
    backdropFilter: "blur(6px)",
    display: "grid",
    placeItems: "center",
    padding: "16px",
    zIndex: 50,
  },
  modalCard: {
    width: "min(480px, 100%)",
    background:
      "linear-gradient(145deg, rgba(16, 46, 22, 0.95), rgba(28, 16, 16, 0.9))",
    border: "1px solid rgba(52, 211, 153, 0.35)",
    boxShadow: "0 24px 60px rgba(0, 0, 0, 0.45)",
    color: palette.text,
    borderRadius: "18px",
    padding: "20px 18px",
    display: "grid",
    gap: "12px",
  },
  modalTitle: {
    margin: 0,
    fontSize: "18px",
    color: "#bbf7d0",
    letterSpacing: "-0.2px",
  },
  modalText: {
    margin: 0,
    color: "#d1fae5",
    lineHeight: 1.5,
  },
  modalAccent: {
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 10px",
    borderRadius: "12px",
    background: "linear-gradient(120deg, rgba(52, 211, 153, 0.16), rgba(239, 68, 68, 0.16))",
    border: "1px solid rgba(239, 68, 68, 0.35)",
    color: "#fecdd3",
    fontWeight: 700,
    width: "fit-content",
  },
  modalActions: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    flexWrap: "wrap",
  },
};

export default styles;
